[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "cellseg_benchmark"
version = "0.2.1"
description = "Tools for assessing the quality of spatial segmentations with focus on vascular cells in the brain."
authors = [{ name = "LMU Munich" }]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "anndata>=0.12.0",
    "dask",
    "geopandas",
    "harmonypy",
    "igraph",
    "IProgress",
    "joblib",
    "leidenalg",
    "numpy",
    "ovrlpy",
    "pandas",
    "plotly",
    "rasterio",
    "rtree",
    "scanpy",
    "scikit-image",
    "scikit-learn",
    "scipy",
    "seaborn",
    "shapely>=2",
    "sopa==2.0.6",
    "spatialdata<0.6.0",
    "spatialdata-io>=0.1.5",
    "tifffile",
    "tqdm",
    "xarray",
]

[project.optional-dependencies]
# only used by notebooks/what_is_this
viz3d = ["pyvista"]

[tool.setuptools.packages.find]
include = ["cellseg_benchmark*"]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes (`F`), pycodestyle (`E`), pycodestyle warnings (`W`)
# Isort (`I`), pep8-naming (`N`), pydocstyle (`D`, google convention as set below)
# Bugbear (`B`), flake8-builtins (`A`)
select = ["E", "F", "I", "D", "A"]
# Ignore: E501 line too long, D100 docstring in public module, D104 Docstring in public package
ignore = ["E501", "F403", "D100", "D104"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# Ignore docstring formats for notebooks
"*.ipynb" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pyflakes]
allowed-unused-imports = ["spatialdata_plot"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"